<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert([
            ['code' => 'AF', 'continent_code' =>  'AS', 'country_name' =>  'Afghanistan', 'full_name' =>  'Islamic Republic of Afghanistan'],
            ['code' => 'AX', 'continent_code' =>  'EU', 'country_name' =>  'Åland Islands', 'full_name' =>  'Åland Islands'],
            ['code' => 'AL', 'continent_code' =>  'EU', 'country_name' =>  'Albania', 'full_name' =>  'Republic of Albania'],
            ['code' => 'DZ', 'continent_code' =>  'AF', 'country_name' =>  'Algeria', 'full_name' =>  'People\'\'s Democratic Republic of Algeria'],
            ['code' => 'AS', 'continent_code' =>  'OC', 'country_name' =>  'American Samoa', 'full_name' =>  'American Samoa'],
            ['code' => 'AD', 'continent_code' =>  'EU', 'country_name' =>  'Andorra', 'full_name' =>  'Principality of Andorra'],
            ['code' => 'AO', 'continent_code' =>  'AF', 'country_name' =>  'Angola', 'full_name' =>  'Republic of Angola'],
            ['code' => 'AI', 'continent_code' =>  'NA', 'country_name' =>  'Anguilla', 'full_name' =>  'Anguilla'],
            ['code' => 'AQ', 'continent_code' =>  'AN', 'country_name' =>  'Antarctica', 'full_name' =>  'Antarctica (the territory South of 60 deg S)'],
            ['code' => 'AG', 'continent_code' =>  'NA', 'country_name' =>  'Antigua and Barbuda', 'full_name' =>  'Antigua and Barbuda'],
            ['code' => 'AR', 'continent_code' =>  'SA', 'country_name' =>  'Argentina', 'full_name' =>  'Argentine Republic'],
            ['code' => 'AM', 'continent_code' =>  'AS', 'country_name' =>  'Armenia', 'full_name' =>  'Republic of Armenia'],
            ['code' => 'AW', 'continent_code' =>  'NA', 'country_name' =>  'Aruba', 'full_name' =>  'Aruba'],
            ['code' => 'AU', 'continent_code' =>  'OC', 'country_name' =>  'Australia', 'full_name' =>  'Commonwealth of Australia'],
            ['code' => 'AT', 'continent_code' =>  'EU', 'country_name' =>  'Austria', 'full_name' =>  'Republic of Austria'],
            ['code' => 'AZ', 'continent_code' =>  'AS', 'country_name' =>  'Azerbaijan', 'full_name' =>  'Republic of Azerbaijan'],
            ['code' => 'BS', 'continent_code' =>  'NA', 'country_name' =>  'Bahamas', 'full_name' =>  'Commonwealth of the Bahamas'],
            ['code' => 'BH', 'continent_code' =>  'AS', 'country_name' =>  'Bahrain', 'full_name' =>  'Kingdom of Bahrain'],
            ['code' => 'BD', 'continent_code' =>  'AS', 'country_name' =>  'Bangladesh', 'full_name' =>  'People\'\'s Republic of Bangladesh'],
            ['code' => 'BB', 'continent_code' =>  'NA', 'country_name' =>  'Barbados', 'full_name' =>  'Barbados'],
            ['code' => 'BY', 'continent_code' =>  'EU', 'country_name' =>  'Belarus', 'full_name' =>  'Republic of Belarus'],
            ['code' => 'BE', 'continent_code' =>  'EU', 'country_name' =>  'Belgium', 'full_name' =>  'Kingdom of Belgium'],
            ['code' => 'BZ', 'continent_code' =>  'NA', 'country_name' =>  'Belize', 'full_name' =>  'Belize'],
            ['code' => 'BJ', 'continent_code' =>  'AF', 'country_name' =>  'Benin', 'full_name' =>  'Republic of Benin'],
            ['code' => 'BM', 'continent_code' =>  'NA', 'country_name' =>  'Bermuda', 'full_name' =>  'Bermuda'],
            ['code' => 'BT', 'continent_code' =>  'AS', 'country_name' =>  'Bhutan', 'full_name' =>  'Kingdom of Bhutan'],
            ['code' => 'BO', 'continent_code' =>  'SA', 'country_name' =>  'Bolivia', 'full_name' =>  'Plurinational State of Bolivia'],
            ['code' => 'BQ', 'continent_code' =>  'NA', 'country_name' =>  'Bonaire, Sint Eustatius and Saba', 'full_name' =>  'Bonaire, Sint Eustatius and Saba'],
            ['code' => 'BA', 'continent_code' =>  'EU', 'country_name' =>  'Bosnia and Herzegovina', 'full_name' =>  'Bosnia and Herzegovina'],
            ['code' => 'BW', 'continent_code' =>  'AF', 'country_name' =>  'Botswana', 'full_name' =>  'Republic of Botswana'],
            ['code' => 'BV', 'continent_code' =>  'AN', 'country_name' =>  'Bouvet Island (Bouvetoya)', 'full_name' => 'Bouvet Island (Bouvetoya)'],
            ['code' => 'BR', 'continent_code' =>  'SA', 'country_name' =>  'Brazil', 'full_name' =>  'Federative Republic of Brazil'],
            ['code' => 'IO', 'continent_code' =>  'AS', 'country_name' =>  'British Indian Ocean Territory (Chagos Archipelago)', 'full_name' => 'British Indian Ocean Territory (Chagos Archipelago)'],
            ['code' => 'VG', 'continent_code' =>  'NA', 'country_name' =>  'British Virgin Islands', 'full_name' =>  'British Virgin Islands'],
            ['code' => 'BN', 'continent_code' =>  'AS', 'country_name' =>  'Brunei Darussalam', 'full_name' =>  'Brunei Darussalam'],
            ['code' => 'BG', 'continent_code' =>  'EU', 'country_name' =>  'Bulgaria', 'full_name' =>  'Republic of Bulgaria'],
            ['code' => 'BF', 'continent_code' =>  'AF', 'country_name' =>  'Burkina Faso', 'full_name' =>  'Burkina Faso'],
            ['code' => 'BI', 'continent_code' =>  'AF', 'country_name' =>  'Burundi', 'full_name' =>  'Republic of Burundi'],
            ['code' => 'KH', 'continent_code' =>  'AS', 'country_name' =>  'Cambodia', 'full_name' =>  'Kingdom of Cambodia'],
            ['code' => 'CM', 'continent_code' =>  'AF', 'country_name' =>  'Cameroon', 'full_name' =>  'Republic of Cameroon'],
            ['code' => 'CA', 'continent_code' =>  'NA', 'country_name' =>  'Canada', 'full_name' =>  'Canada'],
            ['code' => 'CV', 'continent_code' =>  'AF', 'country_name' =>  'Cape Verde', 'full_name' =>  'Republic of Cape Verde'],
            ['code' => 'KY', 'continent_code' =>  'NA', 'country_name' =>  'Cayman Islands', 'full_name' =>  'Cayman Islands'],
            ['code' => 'CF', 'continent_code' =>  'AF', 'country_name' =>  'Central African Republic', 'full_name' =>  'Central African Republic'],
            ['code' => 'TD', 'continent_code' =>  'AF', 'country_name' =>  'Chad', 'full_name' =>  'Republic of Chad'],
            ['code' => 'CL', 'continent_code' =>  'SA', 'country_name' =>  'Chile', 'full_name' =>  'Republic of Chile'],
            ['code' => 'CN', 'continent_code' =>  'AS', 'country_name' =>  'China', 'full_name' =>  'People\'\'s Republic of China'],
            ['code' => 'CX', 'continent_code' =>  'AS', 'country_name' =>  'Christmas Island', 'full_name' =>  'Christmas Island'],
            ['code' => 'CC', 'continent_code' =>  'AS', 'country_name' =>  'Cocos (Keeling) Islands', 'full_name' => 'Cocos (Keeling) Islands'],
            ['code' => 'CO', 'continent_code' =>  'SA', 'country_name' =>  'Colombia', 'full_name' =>  'Republic of Colombia'],
            ['code' => 'KM', 'continent_code' =>  'AF', 'country_name' =>  'Comoros', 'full_name' =>  'Union of the Comoros'],
            ['code' => 'CD', 'continent_code' =>  'AF', 'country_name' =>  'Congo', 'full_name' =>  'Democratic Republic of the Congo'],
            ['code' => 'CG', 'continent_code' =>  'AF', 'country_name' =>  'Congo', 'full_name' =>  'Republic of the Congo'],
            ['code' => 'CK', 'continent_code' =>  'OC', 'country_name' =>  'Cook Islands', 'full_name' =>  'Cook Islands'],
            ['code' => 'CR', 'continent_code' =>  'NA', 'country_name' =>  'Costa Rica', 'full_name' =>  'Republic of Costa Rica'],
            ['code' => 'CI', 'continent_code' =>  'AF', 'country_name' =>  'Cote d\'\'Ivoire', 'full_name' =>  'Republic of Cote d\'\'Ivoire'],
            ['code' => 'HR', 'continent_code' =>  'EU', 'country_name' =>  'Croatia', 'full_name' =>  'Republic of Croatia'],
            ['code' => 'CU', 'continent_code' =>  'NA', 'country_name' =>  'Cuba', 'full_name' =>  'Republic of Cuba'],
            ['code' => 'CW', 'continent_code' =>  'NA', 'country_name' =>  'Curaçao', 'full_name' =>  'Curaçao'],
            ['code' => 'CY', 'continent_code' =>  'AS', 'country_name' =>  'Cyprus', 'full_name' =>  'Republic of Cyprus'],
            ['code' => 'CZ', 'continent_code' =>  'EU', 'country_name' =>  'Czech Republic', 'full_name' =>  'Czech Republic'],
            ['code' => 'DK', 'continent_code' =>  'EU', 'country_name' =>  'Denmark', 'full_name' =>  'Kingdom of Denmark'],
            ['code' => 'DJ', 'continent_code' =>  'AF', 'country_name' =>  'Djibouti', 'full_name' =>  'Republic of Djibouti'],
            ['code' => 'DM', 'continent_code' =>  'NA', 'country_name' =>  'Dominica', 'full_name' =>  'Commonwealth of Dominica'],
            ['code' => 'DO', 'continent_code' =>  'NA', 'country_name' =>  'Dominican Republic', 'full_name' =>  'Dominican Republic'],
            ['code' => 'EC', 'continent_code' =>  'SA', 'country_name' =>  'Ecuador', 'full_name' =>  'Republic of Ecuador'],
            ['code' => 'EG', 'continent_code' =>  'AF', 'country_name' =>  'Egypt', 'full_name' =>  'Arab Republic of Egypt'],
            ['code' => 'SV', 'continent_code' =>  'NA', 'country_name' =>  'El Salvador', 'full_name' =>  'Republic of El Salvador'],
            ['code' => 'GQ', 'continent_code' =>  'AF', 'country_name' =>  'Equatorial Guinea', 'full_name' =>  'Republic of Equatorial Guinea'],
            ['code' => 'ER', 'continent_code' =>  'AF', 'country_name' =>  'Eritrea', 'full_name' =>  'State of Eritrea'],
            ['code' => 'EE', 'continent_code' =>  'EU', 'country_name' =>  'Estonia', 'full_name' =>  'Republic of Estonia'],
            ['code' => 'ET', 'continent_code' =>  'AF', 'country_name' =>  'Ethiopia', 'full_name' =>  'Federal Democratic Republic of Ethiopia'],
            ['code' => 'FO', 'continent_code' =>  'EU', 'country_name' =>  'Faroe Islands', 'full_name' =>  'Faroe Islands'],
            ['code' => 'FK', 'continent_code' =>  'SA', 'country_name' =>  'Falkland Islands (Malvinas)', 'full_name' => 'Falkland Islands (Malvinas)'],
            ['code' => 'FJ', 'continent_code' =>  'OC', 'country_name' =>  'Fiji', 'full_name' =>  'Republic of Fiji'],
            ['code' => 'FI', 'continent_code' =>  'EU', 'country_name' =>  'Finland', 'full_name' =>  'Republic of Finland'],
            ['code' => 'FR', 'continent_code' =>  'EU', 'country_name' =>  'France', 'full_name' =>  'French Republic'],
            ['code' => 'GF', 'continent_code' =>  'SA', 'country_name' =>  'French Guiana', 'full_name' =>  'French Guiana'],
            ['code' => 'PF', 'continent_code' =>  'OC', 'country_name' =>  'French Polynesia', 'full_name' =>  'French Polynesia'],
            ['code' => 'TF', 'continent_code' =>  'AN', 'country_name' =>  'French Southern Territories', 'full_name' =>  'French Southern Territories'],
            ['code' => 'GA', 'continent_code' =>  'AF', 'country_name' =>  'Gabon', 'full_name' =>  'Gabonese Republic'],
            ['code' => 'GM', 'continent_code' =>  'AF', 'country_name' =>  'Gambia', 'full_name' =>  'Republic of the Gambia'],
            ['code' => 'GE', 'continent_code' =>  'AS', 'country_name' =>  'Georgia', 'full_name' =>  'Georgia'],
            ['code' => 'DE', 'continent_code' =>  'EU', 'country_name' =>  'Germany', 'full_name' =>  'Federal Republic of Germany'],
            ['code' => 'GH', 'continent_code' =>  'AF', 'country_name' =>  'Ghana', 'full_name' =>  'Republic of Ghana'],
            ['code' => 'GI', 'continent_code' =>  'EU', 'country_name' =>  'Gibraltar', 'full_name' =>  'Gibraltar'],
            ['code' => 'GR', 'continent_code' =>  'EU', 'country_name' =>  'Greece', 'full_name' =>  'Hellenic Republic Greece'],
            ['code' => 'GL', 'continent_code' =>  'NA', 'country_name' =>  'Greenland', 'full_name' =>  'Greenland'],
            ['code' => 'GD', 'continent_code' =>  'NA', 'country_name' =>  'Grenada', 'full_name' =>  'Grenada'],
            ['code' => 'GP', 'continent_code' =>  'NA', 'country_name' =>  'Guadeloupe', 'full_name' =>  'Guadeloupe'],
            ['code' => 'GU', 'continent_code' =>  'OC', 'country_name' =>  'Guam', 'full_name' =>  'Guam'],
            ['code' => 'GT', 'continent_code' =>  'NA', 'country_name' =>  'Guatemala', 'full_name' =>  'Republic of Guatemala'],
            ['code' => 'GG', 'continent_code' =>  'EU', 'country_name' =>  'Guernsey', 'full_name' =>  'Bailiwick of Guernsey'],
            ['code' => 'GN', 'continent_code' =>  'AF', 'country_name' =>  'Guinea', 'full_name' =>  'Republic of Guinea'],
            ['code' => 'GW', 'continent_code' =>  'AF', 'country_name' =>  'Guinea-Bissau', 'full_name' =>  'Republic of Guinea-Bissau'],
            ['code' => 'GY', 'continent_code' =>  'SA', 'country_name' =>  'Guyana', 'full_name' =>  'Co-operative Republic of Guyana'],
            ['code' => 'HT', 'continent_code' =>  'NA', 'country_name' =>  'Haiti', 'full_name' =>  'Republic of Haiti'],
            ['code' => 'HM', 'continent_code' =>  'AN', 'country_name' =>  'Heard Island and McDonald Islands', 'full_name' =>  'Heard Island and McDonald Islands'],
            ['code' => 'VA', 'continent_code' =>  'EU', 'country_name' =>  'Holy See (Vatican City State)', 'full_name' => 'Holy See (Vatican City State)'],
            ['code' => 'HN', 'continent_code' =>  'NA', 'country_name' =>  'Honduras', 'full_name' =>  'Republic of Honduras'],
            ['code' => 'HK', 'continent_code' =>  'AS', 'country_name' =>  'Hong Kong', 'full_name' =>  'Hong Kong Special Administrative Region of China'],
            ['code' => 'HU', 'continent_code' =>  'EU', 'country_name' =>  'Hungary', 'full_name' =>  'Hungary'],
            ['code' => 'IS', 'continent_code' =>  'EU', 'country_name' =>  'Iceland', 'full_name' =>  'Republic of Iceland'],
            ['code' => 'IN', 'continent_code' =>  'AS', 'country_name' =>  'India', 'full_name' =>  'Republic of India'],
            ['code' => 'ID', 'continent_code' =>  'AS', 'country_name' =>  'Indonesia', 'full_name' =>  'Republic of Indonesia'],
            ['code' => 'IR', 'continent_code' =>  'AS', 'country_name' =>  'Iran', 'full_name' =>  'Islamic Republic of Iran'],
            ['code' => 'IQ', 'continent_code' =>  'AS', 'country_name' =>  'Iraq', 'full_name' =>  'Republic of Iraq'],
            ['code' => 'IE', 'continent_code' =>  'EU', 'country_name' =>  'Ireland', 'full_name' =>  'Ireland'],
            ['code' => 'IM', 'continent_code' =>  'EU', 'country_name' =>  'Isle of Man', 'full_name' =>  'Isle of Man'],
            ['code' => 'IL', 'continent_code' =>  'AS', 'country_name' =>  'Israel', 'full_name' =>  'State of Israel'],
            ['code' => 'IT', 'continent_code' =>  'EU', 'country_name' =>  'Italy', 'full_name' =>  'Italian Republic'],
            ['code' => 'JM', 'continent_code' =>  'NA', 'country_name' =>  'Jamaica', 'full_name' =>  'Jamaica'],
            ['code' => 'JP', 'continent_code' =>  'AS', 'country_name' =>  'Japan', 'full_name' =>  'Japan'],
            ['code' => 'JE', 'continent_code' =>  'EU', 'country_name' =>  'Jersey', 'full_name' =>  'Bailiwick of Jersey'],
            ['code' => 'JO', 'continent_code' =>  'AS', 'country_name' =>  'Jordan', 'full_name' =>  'Hashemite Kingdom of Jordan'],
            ['code' => 'KZ', 'continent_code' =>  'AS', 'country_name' =>  'Kazakhstan', 'full_name' =>  'Republic of Kazakhstan'],
            ['code' => 'KE', 'continent_code' =>  'AF', 'country_name' =>  'Kenya', 'full_name' =>  'Republic of Kenya'],
            ['code' => 'KI', 'continent_code' =>  'OC', 'country_name' =>  'Kiribati', 'full_name' =>  'Republic of Kiribati'],
            ['code' => 'KP', 'continent_code' =>  'AS', 'country_name' =>  'Korea', 'full_name' =>  'Democratic People\'\'s Republic of Korea'],
            ['code' => 'KR', 'continent_code' =>  'AS', 'country_name' =>  'Korea', 'full_name' =>  'Republic of Korea'],
            ['code' => 'KW', 'continent_code' =>  'AS', 'country_name' =>  'Kuwait', 'full_name' =>  'State of Kuwait'],
            ['code' => 'KG', 'continent_code' =>  'AS', 'country_name' =>  'Kyrgyz Republic', 'full_name' =>  'Kyrgyz Republic'],
            ['code' => 'LA', 'continent_code' =>  'AS', 'country_name' =>  'Lao People\'\'s Democratic Republic', 'full_name' =>  'Lao People\'\'s Democratic Republic'],
            ['code' => 'LV', 'continent_code' =>  'EU', 'country_name' =>  'Latvia', 'full_name' =>  'Republic of Latvia'],
            ['code' => 'LB', 'continent_code' =>  'AS', 'country_name' =>  'Lebanon', 'full_name' =>  'Lebanese Republic'],
            ['code' => 'LS', 'continent_code' =>  'AF', 'country_name' =>  'Lesotho', 'full_name' =>  'Kingdom of Lesotho'],
            ['code' => 'LR', 'continent_code' =>  'AF', 'country_name' =>  'Liberia', 'full_name' =>  'Republic of Liberia'],
            ['code' => 'LY', 'continent_code' =>  'AF', 'country_name' =>  'Libya', 'full_name' =>  'Libya'],
            ['code' => 'LI', 'continent_code' =>  'EU', 'country_name' =>  'Liechtenstein', 'full_name' =>  'Principality of Liechtenstein'],
            ['code' => 'LT', 'continent_code' =>  'EU', 'country_name' =>  'Lithuania', 'full_name' =>  'Republic of Lithuania'],
            ['code' => 'LU', 'continent_code' =>  'EU', 'country_name' =>  'Luxembourg', 'full_name' =>  'Grand Duchy of Luxembourg'],
            ['code' => 'MO', 'continent_code' =>  'AS', 'country_name' =>  'Macao', 'full_name' =>  'Macao Special Administrative Region of China'],
            ['code' => 'MK', 'continent_code' =>  'EU', 'country_name' =>  'Macedonia', 'full_name' =>  'Republic of Macedonia'],
            ['code' => 'MG', 'continent_code' =>  'AF', 'country_name' =>  'Madagascar', 'full_name' =>  'Republic of Madagascar'],
            ['code' => 'MW', 'continent_code' =>  'AF', 'country_name' =>  'Malawi', 'full_name' =>  'Republic of Malawi'],
            ['code' => 'MY', 'continent_code' =>  'AS', 'country_name' =>  'Malaysia', 'full_name' =>  'Malaysia'],
            ['code' => 'MV', 'continent_code' =>  'AS', 'country_name' =>  'Maldives', 'full_name' =>  'Republic of Maldives'],
            ['code' => 'ML', 'continent_code' =>  'AF', 'country_name' =>  'Mali', 'full_name' =>  'Republic of Mali'],
            ['code' => 'MT', 'continent_code' =>  'EU', 'country_name' =>  'Malta', 'full_name' =>  'Republic of Malta'],
            ['code' => 'MH', 'continent_code' =>  'OC', 'country_name' =>  'Marshall Islands', 'full_name' =>  'Republic of the Marshall Islands'],
            ['code' => 'MQ', 'continent_code' =>  'NA', 'country_name' =>  'Martinique', 'full_name' =>  'Martinique'],
            ['code' => 'MR', 'continent_code' =>  'AF', 'country_name' =>  'Mauritania', 'full_name' =>  'Islamic Republic of Mauritania'],
            ['code' => 'MU', 'continent_code' =>  'AF', 'country_name' =>  'Mauritius', 'full_name' =>  'Republic of Mauritius'],
            ['code' => 'YT', 'continent_code' =>  'AF', 'country_name' =>  'Mayotte', 'full_name' =>  'Mayotte'],
            ['code' => 'MX', 'continent_code' =>  'NA', 'country_name' =>  'Mexico', 'full_name' =>  'United Mexican States'],
            ['code' => 'FM', 'continent_code' =>  'OC', 'country_name' =>  'Micronesia', 'full_name' =>  'Federated States of Micronesia'],
            ['code' => 'MD', 'continent_code' =>  'EU', 'country_name' =>  'Moldova', 'full_name' =>  'Republic of Moldova'],
            ['code' => 'MC', 'continent_code' =>  'EU', 'country_name' =>  'Monaco', 'full_name' =>  'Principality of Monaco'],
            ['code' => 'MN', 'continent_code' =>  'AS', 'country_name' =>  'Mongolia', 'full_name' =>  'Mongolia'],
            ['code' => 'ME', 'continent_code' =>  'EU', 'country_name' =>  'Montenegro', 'full_name' =>  'Montenegro'],
            ['code' => 'MS', 'continent_code' =>  'NA', 'country_name' =>  'Montserrat', 'full_name' =>  'Montserrat'],
            ['code' => 'MA', 'continent_code' =>  'AF', 'country_name' =>  'Morocco', 'full_name' =>  'Kingdom of Morocco'],
            ['code' => 'MZ', 'continent_code' =>  'AF', 'country_name' =>  'Mozambique', 'full_name' =>  'Republic of Mozambique'],
            ['code' => 'MM', 'continent_code' =>  'AS', 'country_name' =>  'Myanmar', 'full_name' =>  'Republic of the Union of Myanmar'],
            ['code' => 'NA', 'continent_code' =>  'AF', 'country_name' =>  'Namibia', 'full_name' =>  'Republic of Namibia'],
            ['code' => 'NR', 'continent_code' =>  'OC', 'country_name' =>  'Nauru', 'full_name' =>  'Republic of Nauru'],
            ['code' => 'NP', 'continent_code' =>  'AS', 'country_name' =>  'Nepal', 'full_name' =>  'Federal Democratic Republic of Nepal'],
            ['code' => 'NL', 'continent_code' =>  'EU', 'country_name' =>  'Netherlands', 'full_name' =>  'Kingdom of the Netherlands'],
            ['code' => 'NC', 'continent_code' =>  'OC', 'country_name' =>  'New Caledonia', 'full_name' =>  'New Caledonia'],
            ['code' => 'NZ', 'continent_code' =>  'OC', 'country_name' =>  'New Zealand', 'full_name' =>  'New Zealand'],
            ['code' => 'NI', 'continent_code' =>  'NA', 'country_name' =>  'Nicaragua', 'full_name' =>  'Republic of Nicaragua'],
            ['code' => 'NE', 'continent_code' =>  'AF', 'country_name' =>  'Niger', 'full_name' =>  'Republic of Niger'],
            ['code' => 'NG', 'continent_code' =>  'AF', 'country_name' =>  'Nigeria', 'full_name' =>  'Federal Republic of Nigeria'],
            ['code' => 'NU', 'continent_code' =>  'OC', 'country_name' =>  'Niue', 'full_name' =>  'Niue'],
            ['code' => 'NF', 'continent_code' =>  'OC', 'country_name' =>  'Norfolk Island', 'full_name' =>  'Norfolk Island'],
            ['code' => 'MP', 'continent_code' =>  'OC', 'country_name' =>  'Northern Mariana Islands', 'full_name' =>  'Commonwealth of the Northern Mariana Islands'],
            ['code' => 'NO', 'continent_code' =>  'EU', 'country_name' =>  'Norway', 'full_name' =>  'Kingdom of Norway'],
            ['code' => 'OM', 'continent_code' =>  'AS', 'country_name' =>  'Oman', 'full_name' =>  'Sultanate of Oman'],
            ['code' => 'PK', 'continent_code' =>  'AS', 'country_name' =>  'Pakistan', 'full_name' =>  'Islamic Republic of Pakistan'],
            ['code' => 'PW', 'continent_code' =>  'OC', 'country_name' =>  'Palau', 'full_name' =>  'Republic of Palau'],
            ['code' => 'PS', 'continent_code' =>  'AS', 'country_name' =>  'Palestine', 'full_name' =>  'State of Palestine'],
            ['code' => 'PA', 'continent_code' =>  'NA', 'country_name' =>  'Panama', 'full_name' =>  'Republic of Panama'],
            ['code' => 'PG', 'continent_code' =>  'OC', 'country_name' =>  'Papua New Guinea', 'full_name' =>  'Independent State of Papua New Guinea'],
            ['code' => 'PY', 'continent_code' =>  'SA', 'country_name' =>  'Paraguay', 'full_name' =>  'Republic of Paraguay'],
            ['code' => 'PE', 'continent_code' =>  'SA', 'country_name' =>  'Peru', 'full_name' =>  'Republic of Peru'],
            ['code' => 'PH', 'continent_code' =>  'AS', 'country_name' =>  'Philippines', 'full_name' =>  'Republic of the Philippines'],
            ['code' => 'PN', 'continent_code' =>  'OC', 'country_name' =>  'Pitcairn Islands', 'full_name' =>  'Pitcairn Islands'],
            ['code' => 'PL', 'continent_code' =>  'EU', 'country_name' =>  'Poland', 'full_name' =>  'Republic of Poland'],
            ['code' => 'PT', 'continent_code' =>  'EU', 'country_name' =>  'Portugal', 'full_name' =>  'Portuguese Republic'],
            ['code' => 'PR', 'continent_code' =>  'NA', 'country_name' =>  'Puerto Rico', 'full_name' =>  'Commonwealth of Puerto Rico'],
            ['code' => 'QA', 'continent_code' =>  'AS', 'country_name' =>  'Qatar', 'full_name' =>  'State of Qatar'],
            ['code' => 'RE', 'continent_code' =>  'AF', 'country_name' =>  'Réunion', 'full_name' =>  'Réunion'],
            ['code' => 'RO', 'continent_code' =>  'EU', 'country_name' =>  'Romania', 'full_name' =>  'Romania'],
            ['code' => 'RU', 'continent_code' =>  'EU', 'country_name' =>  'Russian Federation', 'full_name' =>  'Russian Federation'],
            ['code' => 'RW', 'continent_code' =>  'AF', 'country_name' =>  'Rwanda', 'full_name' =>  'Republic of Rwanda'],
            ['code' => 'BL', 'continent_code' =>  'NA', 'country_name' =>  'Saint Barthélemy', 'full_name' =>  'Saint Barthélemy'],
            ['code' => 'SH', 'continent_code' =>  'AF', 'country_name' =>  'Saint Helena, Ascension and Tristan da Cunha', 'full_name' => 'Saint Helena, Ascension and Tristan da Cunha'],
            ['code' => 'KN', 'continent_code' =>  'NA', 'country_name' =>  'Saint Kitts and Nevis', 'full_name' =>  'Federation of Saint Kitts and Nevis'],
            ['code' => 'LC', 'continent_code' =>  'NA', 'country_name' =>  'Saint Lucia', 'full_name' =>  'Saint Lucia'],
            ['code' => 'MF', 'continent_code' =>  'NA', 'country_name' =>  'Saint Martin', 'full_name' =>  'Saint Martin (French part)'],
            ['code' => 'PM', 'continent_code' =>  'NA', 'country_name' =>  'Saint Pierre and Miquelon', 'full_name' =>  'Saint Pierre and Miquelon'],
            ['code' => 'VC', 'continent_code' =>  'NA', 'country_name' =>  'Saint Vincent and the Grenadines', 'full_name' =>  'Saint Vincent and the Grenadines'],
            ['code' => 'WS', 'continent_code' =>  'OC', 'country_name' =>  'Samoa', 'full_name' =>  'Independent State of Samoa'],
            ['code' => 'SM', 'continent_code' =>  'EU', 'country_name' =>  'San Marino', 'full_name' =>  'Republic of San Marino'],
            ['code' => 'ST', 'continent_code' =>  'AF', 'country_name' =>  'Sao Tome and Principe', 'full_name' =>  'Democratic Republic of Sao Tome and Principe'],
            ['code' => 'SA', 'continent_code' =>  'AS', 'country_name' =>  'Saudi Arabia', 'full_name' =>  'Kingdom of Saudi Arabia'],
            ['code' => 'SN', 'continent_code' =>  'AF', 'country_name' =>  'Senegal', 'full_name' =>  'Republic of Senegal'],
            ['code' => 'RS', 'continent_code' =>  'EU', 'country_name' =>  'Serbia', 'full_name' =>  'Republic of Serbia'],
            ['code' => 'SC', 'continent_code' =>  'AF', 'country_name' =>  'Seychelles', 'full_name' =>  'Republic of Seychelles'],
            ['code' => 'SL', 'continent_code' =>  'AF', 'country_name' =>  'Sierra Leone', 'full_name' =>  'Republic of Sierra Leone'],
            ['code' => 'SG', 'continent_code' =>  'AS', 'country_name' =>  'Singapore', 'full_name' =>  'Republic of Singapore'],
            ['code' => 'SX', 'continent_code' =>  'NA', 'country_name' =>  'Sint Maarten (Dutch part)', 'full_name' => 'Sint Maarten (Dutch part)'],
            ['code' => 'SK', 'continent_code' =>  'EU', 'country_name' =>  'Slovakia (Slovak Republic)', 'full_name' => 'Slovakia (Slovak Republic)'],
            ['code' => 'SI', 'continent_code' =>  'EU', 'country_name' =>  'Slovenia', 'full_name' =>  'Republic of Slovenia'],
            ['code' => 'SB', 'continent_code' =>  'OC', 'country_name' =>  'Solomon Islands', 'full_name' =>  'Solomon Islands'],
            ['code' => 'SO', 'continent_code' =>  'AF', 'country_name' =>  'Somalia', 'full_name' =>  'Federal Republic of Somalia'],
            ['code' => 'ZA', 'continent_code' =>  'AF', 'country_name' =>  'South Africa', 'full_name' =>  'Republic of South Africa'],
            ['code' => 'GS', 'continent_code' =>  'AN', 'country_name' =>  'South Georgia and the South Sandwich Islands', 'full_name' =>  'South Georgia and the South Sandwich Islands'],
            ['code' => 'SS', 'continent_code' =>  'AF', 'country_name' =>  'South Sudan', 'full_name' =>  'Republic of South Sudan'],
            ['code' => 'ES', 'continent_code' =>  'EU', 'country_name' =>  'Spain', 'full_name' =>  'Kingdom of Spain'],
            ['code' => 'LK', 'continent_code' =>  'AS', 'country_name' =>  'Sri Lanka', 'full_name' =>  'Democratic Socialist Republic of Sri Lanka'],
            ['code' => 'SD', 'continent_code' =>  'AF', 'country_name' =>  'Sudan', 'full_name' =>  'Republic of Sudan'],
            ['code' => 'SR', 'continent_code' =>  'SA', 'country_name' =>  'Suriname', 'full_name' =>  'Republic of Suriname'],
            ['code' => 'SJ', 'continent_code' =>  'EU', 'country_name' =>  'Svalbard & Jan Mayen Islands', 'full_name' =>  'Svalbard & Jan Mayen Islands'],
            ['code' => 'SZ', 'continent_code' =>  'AF', 'country_name' =>  'Swaziland', 'full_name' =>  'Kingdom of Swaziland'],
            ['code' => 'SE', 'continent_code' =>  'EU', 'country_name' =>  'Sweden', 'full_name' =>  'Kingdom of Sweden'],
            ['code' => 'CH', 'continent_code' =>  'EU', 'country_name' =>  'Switzerland', 'full_name' =>  'Swiss Confederation'],
            ['code' => 'SY', 'continent_code' =>  'AS', 'country_name' =>  'Syrian Arab Republic', 'full_name' =>  'Syrian Arab Republic'],
            ['code' => 'TW', 'continent_code' =>  'AS', 'country_name' =>  'Taiwan', 'full_name' =>  'Taiwan, Province of China'],
            ['code' => 'TJ', 'continent_code' =>  'AS', 'country_name' =>  'Tajikistan', 'full_name' =>  'Republic of Tajikistan'],
            ['code' => 'TZ', 'continent_code' =>  'AF', 'country_name' =>  'Tanzania', 'full_name' =>  'United Republic of Tanzania'],
            ['code' => 'TH', 'continent_code' =>  'AS', 'country_name' =>  'Thailand', 'full_name' =>  'Kingdom of Thailand'],
            ['code' => 'TL', 'continent_code' =>  'AS', 'country_name' =>  'Timor-Leste', 'full_name' =>  'Democratic Republic of Timor-Leste'],
            ['code' => 'TG', 'continent_code' =>  'AF', 'country_name' =>  'Togo', 'full_name' =>  'Togolese Republic'],
            ['code' => 'TK', 'continent_code' =>  'OC', 'country_name' =>  'Tokelau', 'full_name' =>  'Tokelau'],
            ['code' => 'TO', 'continent_code' =>  'OC', 'country_name' =>  'Tonga', 'full_name' =>  'Kingdom of Tonga'],
            ['code' => 'TT', 'continent_code' =>  'NA', 'country_name' =>  'Trinidad and Tobago', 'full_name' =>  'Republic of Trinidad and Tobago'],
            ['code' => 'TN', 'continent_code' =>  'AF', 'country_name' =>  'Tunisia', 'full_name' =>  'Tunisian Republic'],
            ['code' => 'TR', 'continent_code' =>  'AS', 'country_name' =>  'Turkey', 'full_name' =>  'Republic of Turkey'],
            ['code' => 'TM', 'continent_code' =>  'AS', 'country_name' =>  'Turkmenistan', 'full_name' =>  'Turkmenistan'],
            ['code' => 'TC', 'continent_code' =>  'NA', 'country_name' =>  'Turks and Caicos Islands', 'full_name' =>  'Turks and Caicos Islands'],
            ['code' => 'TV', 'continent_code' =>  'OC', 'country_name' =>  'Tuvalu', 'full_name' =>  'Tuvalu'],
            ['code' => 'UG', 'continent_code' =>  'AF', 'country_name' =>  'Uganda', 'full_name' =>  'Republic of Uganda'],
            ['code' => 'UA', 'continent_code' =>  'EU', 'country_name' =>  'Ukraine', 'full_name' =>  'Ukraine'],
            ['code' => 'AE', 'continent_code' =>  'AS', 'country_name' =>  'United Arab Emirates', 'full_name' =>  'United Arab Emirates'],
            ['code' => 'GB', 'continent_code' =>  'EU', 'country_name' =>  'United Kingdom of Great Britain & Northern Ireland', 'full_name' =>  'United Kingdom of Great Britain & Northern Ireland'],
            ['code' => 'US', 'continent_code' =>  'NA', 'country_name' =>  'United States of America', 'full_name' =>  'United States of America'],
            ['code' => 'UM', 'continent_code' =>  'OC', 'country_name' =>  'United States Minor Outlying Islands', 'full_name' =>  'United States Minor Outlying Islands'],
            ['code' => 'VI', 'continent_code' =>  'NA', 'country_name' =>  'United States Virgin Islands', 'full_name' =>  'United States Virgin Islands'],
            ['code' => 'UY', 'continent_code' =>  'SA', 'country_name' =>  'Uruguay', 'full_name' =>  'Eastern Republic of Uruguay'],
            ['code' => 'UZ', 'continent_code' =>  'AS', 'country_name' =>  'Uzbekistan', 'full_name' =>  'Republic of Uzbekistan'],
            ['code' => 'VU', 'continent_code' =>  'OC', 'country_name' =>  'Vanuatu', 'full_name' =>  'Republic of Vanuatu'],
            ['code' => 'VE', 'continent_code' =>  'SA', 'country_name' =>  'Venezuela', 'full_name' =>  'Bolivarian Republic of Venezuela'],
            ['code' => 'VN', 'continent_code' =>  'AS', 'country_name' =>  'Vietnam', 'full_name' =>  'Socialist Republic of Vietnam'],
            ['code' => 'WF', 'continent_code' =>  'OC', 'country_name' =>  'Wallis and Futuna', 'full_name' =>  'Wallis and Futuna'],
            ['code' => 'EH', 'continent_code' =>  'AF', 'country_name' =>  'Western Sahara', 'full_name' =>  'Western Sahara'],
            ['code' => 'YE', 'continent_code' =>  'AS', 'country_name' =>  'Yemen', 'full_name' =>  'Yemen'],
            ['code' => 'ZM', 'continent_code' =>  'AF', 'country_name' =>  'Zambia', 'full_name' =>  'Republic of Zambia'],
            ['code' => 'ZW', 'continent_code' =>  'AF', 'country_name' =>  'Zimbabwe', 'full_name' =>  'Republic of Zimbabwe'],
        ]);
    }
}
